- name: Run ThumbgenDemo
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create temporary directory for the related artifacts
      tempfile:
        state: directory
        prefix: radon-ctt-opera_
      register: temp_dir

    - name: copy docker-compose to the temporary directory
      copy:
        src: docker-compose.yml
        dest: "{{ temp_dir.path }}/docker-compose.yml"

    - name: run docker-compose from shell
      shell: docker-compose -f "{{ temp_dir.path }}/docker-compose.yml" up -d front-end edge-router catalogue catalogue-db carts carts-db orders orders-db shipping queue-master rabbitmq payment user user-db
