version: '2'

services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    hostname: front-end
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - external
      - secure
      - internal
  edge-router:
    image: weaveworksdemos/edge-router:0.1.1
    ports:
      - '80:80'
      - '8080:8080'
    hostname: edge-router
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - external
  catalogue:
    image: weaveworksdemos/catalogue:0.3.5
    hostname: catalogue
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - external
  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0
    hostname: catalogue-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
    networks:
      - external
  carts:
    image: weaveworksdemos/carts:0.4.8
    hostname: carts
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - internal
  carts-db:
    image: mongo:3.4
    hostname: carts-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - internal
  orders:
    image: weaveworksdemos/orders:0.4.7
    hostname: orders
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - internal
      - secure
      - backoffice
  orders-db:
    image: mongo:3.4
    hostname: orders-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - internal
  shipping:
    image: weaveworksdemos/shipping:0.4.8
    hostname: shipping
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
    networks:
      - backoffice
  queue-master:
    image: weaveworksdemos/queue-master:0.3.1
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - backoffice
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - backoffice
  payment:
    image: weaveworksdemos/payment:0.4.3
    hostname: payment
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - secure
  user:
    image: weaveworksdemos/user:0.4.4
    hostname: user
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - MONGO_HOST=user-db:27017
      - reschedule=on-node-failure
    networks:
      - secure
  user-db:
    image: weaveworksdemos/user-db:0.4.0
    hostname: user-db
    dns: 172.17.0.1
    dns_search: weave.local
    restart: always
    environment:
      - reschedule=on-node-failure
    networks:
      - secure
  user-sim:
    image: weaveworksdemos/load-test:0.1.1
    hostname: user-simulator
    domainname: weave.local
    networks:
      - external
    command: "-d 60 -r 200 -c 2 -h edge-router"
networks:
  external:
    driver: weavemesh
  secure:
    driver: weavemesh
  internal:
    driver: weavemesh
  backoffice:
    driver: weavemesh
